name: Reuse2

on:
  workflow_call:
   
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        run: |
          echo "printing"
          ls -R
          
    
